Add branding setting
claudiob/yt pull request #292
Opened 2016-09-29 13:13 UTC by jakubonty

Added branding setting, which contains banner url of a channel.

2018-01-18 17:47 UTC, FunkyloverOne commented
Why is this not yet merged?

2018-02-13 16:42 UTC, FunkyloverOne commented
@jakubonty I suspect that your PR will not be merged without specs. Could you provide them please? :D

2019-05-31 21:34 UTC, dgb commented
Hi there,

My name is Derek and I'm now one of the maintainers of the Yt gem. I want to both thank you for your contribution and apologize for the lack of feedback on your pull request. Maintaining an open source project like Yt is a pretty big job, and we're taking steps to prioritize maintenance and development of the project. We're hoping to review community contributions on a regular basis, as well as provide a roadmap for our development plans.

As part of this process we're going through the open PRs and taking action on each one, and for this PR we've chosen to review it. You can expect some more specific feedback in the next week or so.

Thanks again for your contribution, and please let us know if you have any questions or comments.

2019-06-19 17:38 UTC, dgb requested changes
I'm 👍 on adding this feature so long as tests are added; It can probably just be a couple cases in the `as_account` channel spec, for reading/writing this attribute.

2019-06-19 17:38 UTC, dgb commented on lib/yt/collections/branding_settings.rb
> +        params = {max_results: 50, part: 'brandingSettings'}
I think `max_results` is configurable in other requests--we should mimic that (or omit it if its irrelevant in this particular case).

2020-09-13 17:29 UTC, FunkyloverOne commented
Hey @dgb, could you please give some more assistance on this one? 
I really need this feature for years now, but I do not have any idea how this gem actually works inside and how to test it at all :c

2022-10-29 17:50 UTC, kangkyu commented
Thank you for a really good pull request and it will be nice if we have brandingSettings but `brandingSettings.image` is deprecated from YouTube for now. Closing

2022-10-29 17:50 UTC, closed without merging