Feature/captions
claudiob/yt pull request #332
Opened 2018-02-23 10:06 UTC by jponc

## Changes
- Downloads the file in chunks, built by @KieranP 
- Added captions associations for `Yt::Video` object

2018-02-25 23:07 UTC, yanshiyason commented
I was also in the process of implementing the same feature!

2018-02-26 10:18 UTC, jponc commented
@yanshiyason did you manage to implement captions insert?

2018-02-26 10:44 UTC, yanshiyason commented
@jponc No, I was trying to retrieve captions from public videos but after
googling a bit it seems like you can only download captions if you are the
owner of the video.. so I was going to do further research on how to bypass
this restriction

On Mon, Feb 26, 2018 at 19:18 Julian Ponce <notifications@github.com> wrote:

> @yanshiyason <https://github.com/yanshiyason> did you manage to implement
> captions insert?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Fullscreen/yt/pull/332#issuecomment-368453637>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AK1Qo9Wzs_YT6ZVHAa0uWpeohm6bo9FWks5tYoTrgaJpZM4SQpgS>
> .
>

2018-02-27 06:26 UTC, jponc commented
@yanshiyason When you say `retrieve` Do you want to get a list of captions? Because this PR is built for that.

I read the official Youtube API V3 documentation and they allow caption downloads as long as you provide them the identifier.

https://developers.google.com/youtube/v3/docs/captions/download

2018-02-27 07:43 UTC, yanshiyason commented
@jponc the V3 api’s captions endpoint has a ˋlist` method which shows you
metadata about the captions but you must use the ˋdownload` method to see
the actual content. This requires ownership of the video though. This is
what I want to bypass.
On Tue, Feb 27, 2018 at 15:26 Julian Ponce <notifications@github.com> wrote:

> @yanshiyason <https://github.com/yanshiyason> When you say retrieve Do
> you want to get a list of captions? Because this PR is built for that.
>
> I read the official Youtube API V3 documentation and they allow caption
> downloads as long as you provide them the identifier.
>
> https://developers.google.com/youtube/v3/docs/captions/download
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Fullscreen/yt/pull/332#issuecomment-368761262>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AK1Qo_nTUVcxTnOzfh9hNgliVbXOhTkAks5tY5_5gaJpZM4SQpgS>
> .
>

2018-03-15 07:26 UTC, lucascaton commented
For those who want a work around to get subtitles quickly (without even having a API key), you can use [youtube-dl](https://github.com/rg3/youtube-dl) with some flags:

```sh
youtube-dl --write-auto-sub --convert-subs=lrc --sub-lang=pt <video_id>;
```

Ps.: Replace `--sub-lang=pt` (Portuguese) with `--sub-lang=en` for English or with any other you want :)

2018-03-15 10:20 UTC, yanshiyason commented
Sweet!
On Thu, Mar 15, 2018 at 16:26 Lucas Caton <notifications@github.com> wrote:

> For those who want a work around to get subtitles quickly (without even
> having a API key), you can use youtube-dl
> <https://github.com/rg3/youtube-dl> with some flags:
>
> youtube-dl --write-auto-sub --convert-subs=lrc --sub-lang=pt <video_id>;
>
> Ps.: Replace --sub-lang=pt (Portuguese) with --sub-lang=en for English or
> with any other you want :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Fullscreen/yt/pull/332#issuecomment-373285020>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AK1QozcyXcyBf94TYnRyWzZuJirMnK4Lks5teheSgaJpZM4SQpgS>
> .
>

2018-03-19 06:59 UTC, jponc commented
I can't seem to find an easy way to integrate caption uploads to this PR. Primarily because the "upload" functionality for a video is tightly coupled with thumbnails. Any suggestions?

2019-05-31 21:34 UTC, dgb commented
Hi there,

My name is Derek and I'm now one of the maintainers of the Yt gem. I want to both thank you for your contribution and apologize for the lack of feedback on your pull request. Maintaining an open source project like Yt is a pretty big job, and we're taking steps to prioritize maintenance and development of the project. We're hoping to review community contributions on a regular basis, as well as provide a roadmap for our development plans.

As part of this process we're going through the open PRs and taking action on each one, and for this PR we've chosen to review it. You can expect some more specific feedback in the next week or so.

Thanks again for your contribution, and please let us know if you have any questions or comments.

2019-06-05 22:00 UTC, kangkyu commented on lib/yt/models/account.rb
> +        return false
it always returns `false` is it intended for development?

2019-06-19 17:33 UTC, dgb requested changes
Overall this LGTM but it needs tests before merging. Thanks for bearing with us!

2019-06-19 17:33 UTC, dgb commented on lib/yt/models/base.rb
> +      def fetch_remote_file(url)
I'm not sure I understand if/how this is different from what `open-uri` does.

2019-06-19 17:33 UTC, dgb commented on lib/yt/models/account.rb
> +        file =
Is this change necessary? We're using open-uri so this should Just Work ™️ .

2019-06-19 17:33 UTC, dgb commented on lib/yt/models/base.rb
> +require 'open-uri'
This is `require`d elsewhere (in the account model).

2019-07-01 05:05 UTC, jponc commented
Thanks for the recommendations, yeah I haven't really touched the forked branch for quite a while now and I've been really busy lately. Will try next week to do the necessary fix and update this PR. Cheers guys

2020-02-14 22:50 UTC, 0xStarcat commented
This feature looks amazing!! :)

2020-12-30 14:47 UTC, NicosKaralis commented
Any updates on this?

2022-05-23 14:41 UTC, fw42 commented
Any chance to get this shipped? Would be awesome. Thanks!

2022-05-24 00:16 UTC, jponc commented
Hi guys sorry for the late reply on this, I haven't touched this library (or even Ruby for a while now), so I'm going to close this PR and would just defer the changes to anyone that might be interested.

2022-05-24 00:16 UTC, closed without merging